FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/stockwatch-naaa0/firestore/indexes?create_composite=ClJwcm9qZWN0cy9zdG9ja3dhdGNoLW5hYWEwL2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy9zaGlwbWVudHMvaW5kZXhlcy9fEAEaCgoGc3RhdHVzEAEaDwoLbGFzdFVwZGF0ZWQQAhoMCghfX25hbWVfXxAC